

#ifndef REMOTE_H_
#define REMOTE_H_

void REMOTE_INIT();

int REMOTE_MOVE_PRESSED();
int REMOTE_LEFT_PRESSED();
int REMOTE_RIGHT_PRESSED();
int REMOTE_G_PRESSED();

void REMOTE_MOVE();
void REMOTE_LEFT();
void REMOTE_RIGHT();
void REMOTE_G();


#endif /* REMOTE_H_ */